# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_post',
        ),
    ]
