# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170811_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='category_post',
            name='label',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='category_post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.category_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_attached',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
