# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170814_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Category_post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_post',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
