# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170816_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
