# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170816_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='2', null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Category_post'),
        ),
    ]
