# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170818_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_attached',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.user_directory_path),
        ),
    ]
