# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boutique', '0025_auto_20170803_1359'),
        ('reactions', '0003_reaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.Product'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(blank=True, choices=[('NORMAL', 'normal'), ('SMILE', 'smile'), ('LOVE', 'love'), ('WISH', 'wish')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set([('user', 'product')]),
        ),
    ]
