# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0004_auto_20170807_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(blank=True, choices=[('NORMAL', 'normal'), ('SMILE', 'smile'), ('LOVE', 'love'), ('WISH', 'wish'), ('SHARE', 'share')], max_length=255, null=True),
        ),
    ]
