# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170814_1401'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reactions', '0009_auto_20170808_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('reaction', models.CharField(blank=True, choices=[('LIKE', 'like'), ('DISLIKE', 'dislike')], max_length=255, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reaction_post',
            unique_together=set([('user', 'post')]),
        ),
    ]
