# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0010_auto_20170814_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction_post',
            name='reaction',
            field=models.CharField(blank=True, choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), ('COMMENT', 'comment')], max_length=255, null=True),
        ),
    ]
