# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0011_auto_20170816_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(blank=True, choices=[('normal', 'normal'), ('smile', 'smile'), ('love', 'love'), ('wish', 'wish')], max_length=255, null=True),
        ),
    ]
