# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_auto_20170720_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, choices=[('Clothing_and_accessories', 'Clothing_and_accessories'), ('Jewelry', 'Jewelry'), ('Creative_Supply', 'Creative_Supply'), ('weddings', 'weddings'), ('House', 'House'), ('Child_and_Baby', 'Child_and_Baby')], default=None, on_delete=django.db.models.deletion.CASCADE, to='boutique.Category'),
        ),
    ]
