# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_auto_20170720_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='label',
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
    ]
