# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0011_auto_20170720_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='boutique.Category'),
        ),
    ]
