# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0012_auto_20170720_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Hand_Made', 'Hand_Made'), ('Vintage', 'Vintage')], default=None, max_length=20),
        ),
    ]
