# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0013_auto_20170720_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('HM', 'Hand_Made'), ('VTG', 'Vintage')], default=None, max_length=20),
        ),
    ]
