# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0015_auto_20170720_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Hand_Made', 'Hand_Made'), ('Vintage', 'Vintage')], default=None, max_length=20),
        ),
    ]
