# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:01
from __future__ import unicode_literals

import boutique.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0016_auto_20170720_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_logo',
            field=models.FileField(upload_to=boutique.models.user_directory_path),
        ),
    ]
