# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0020_auto_20170801_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercant',
            name='name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='commercant',
            name='tel',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='commercant',
            name='description',
            field=models.TextField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
