# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0022_reactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reactions',
            new_name='Reaction',
        ),
    ]
