# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0023_auto_20170803_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reaction',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='boutique.Reaction'),
        ),
    ]
