# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0026_auto_20170809_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
