# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0027_auto_20170809_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
