# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 21:10
from __future__ import unicode_literals

import boutique.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0028_auto_20170809_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic1',
            field=models.ImageField(null=True, upload_to=boutique.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic2',
            field=models.ImageField(null=True, upload_to=boutique.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic3',
            field=models.ImageField(null=True, upload_to=boutique.models.user_directory_path),
        ),
    ]
