# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0029_auto_20170809_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date',)},
        ),
    ]
