# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0030_auto_20170814_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, default=None, max_length=250),
        ),
    ]
