# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0035_auto_20170818_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
