# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0037_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(blank=True, choices=[('baby', 'BABY'), ('child', 'CHILD'), ('teenager', 'TEENAGER'), ('adult', 'ADULT')], default=None, max_length=10),
        ),
    ]
