# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0044_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(blank=True, choices=[('Baby', 'Baby'), ('Child', 'Child'), ('Teenager', 'Teenager'), ('Adult', 'Adult')], default=None, max_length=10),
        ),
    ]
