# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boutique', '0045_auto_20170822_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Msg_Parametre',
            field=models.TextField(default='Can I help you?'),
        ),
        migrations.AddField(
            model_name='shop',
            name='visitors',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
