# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0049_auto_20170825_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='boutique.Product'),
        ),
    ]
