# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messenger.Message')),
            ],
        ),
    ]
