# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_remove_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
