# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170814_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('normal', 'normal'), ('smile', 'smile'), ('love', 'love'), ('wish', 'wish'), ('like', 'like'), ('dislike', 'dislike'), ('comment', 'comment')], max_length=255),
        ),
    ]
